### ISSUE TITLE
Setup pipelines / releases for XRTK.Example Hub application

### ISSUE THREAD

**Issue by FejZa** [XRTK/Examples#6]
## Is your feature request related to a problem? Please describe.

It's time the Examples repo gets some love. My idea is to setup build pipelines that will output an executable/apk etc. for each platform XRTK currently supports officially. That build should always mirror the latest release of XRTK. For now it will only be the base scene with nothing else. But that alone gives everyone the opportunity to just deploy and see if controllers etc. are working.

## Describe the solution you'd like

For starters suggesting the following:
- [ ] In the XRTK.Examples project add the BaseScene to the "scene in build" list at index 0
- [ ] Create Pipeline building the XRTK.Examples project to Windows Standalone using OpenVR
- [ ] Create Pipeline building the XRTK.Examples project to Windows Mixed Reality
- [ ] Create Pipeline building the XRTK.Examples project to Oculus (Android)
- [ ] Set triggers to trigger a build whenever `development` is updated

**Comment by StephenHodgson** [comment]
Let's leave this open. Still something we wanna do.
